game/GameStuff/GameStuff/Models/DomainModels/Cart.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;

namespace GameStuff.Models
{
    public class Cart
    {
        private const string CartKey = "mycart";
        private const string CountKey = "mycount";

        private List<CartItem> items { get; set; }
        private List<CartItemDTO> storedItems { get; set; }

        private ISession session { get; set; }
        private IRequestCookieCollection requestCookies { get; set; }
        private IResponseCookies responseCookies { get; set; }

        public Cart(HttpContext ctx)
        {
            session = ctx.Session;
            requestCookies = ctx.Request.Cookies;
            responseCookies = ctx.Response.Cookies;
        }

        public void Load(Repository<Game> data)
        {
            items = session.GetObject<List<CartItem>>(CartKey);
            if (items == null) {
                items = new List<CartItem>();
                storedItems = requestCookies.GetObject<List<CartItemDTO>>(CartKey);
            }
            if (storedItems?.Count > items?.Count) {
                foreach (CartItemDTO storedItem in storedItems) {
                    var game = data.Get(new QueryOptions<Game> {
                        Include = "GameDevelopers.Developer, Genre",
                        Where = b => b.GameId == storedItem.GameId
                    });
                    if (game != null) {
                        var dto = new GameDTO();
                        dto.Load(game);

                        CartItem item = new CartItem {
                            Game = dto,
                            Quantity = storedItem.Quantity
                        };
                        items.Add(item);
                    }
                }
                Save();
            }
        }

        public double Subtotal => items.Sum(i => i.Subtotal);
        public int? Count => session.GetInt32(CountKey) ?? requestCookies.GetInt32(CountKey);
        public IEnumerable<CartItem> List => items;

        public CartItem GetById(int id) => 
            items.FirstOrDefault(ci => ci.Game.GameId == id);

       public void Add(CartItem item) {
            var itemInCart = GetById(item.Game.GameId);
           
            if (itemInCart == null) {
                items.Add(item);
            }
            else {  
                itemInCart.Quantity += 1;
            }
        }

        public void Edit(CartItem item)
        {
            var itemInCart = GetById(item.Game.GameId);
            if (itemInCart != null) {
                itemInCart.Quantity = item.Quantity;
            }
        }

        public void Remove(CartItem item) => items.Remove(item);
        public void Clear() => items.Clear();
        
        public void Save() {
            if (items.Count == 0) {
                session.Remove(CartKey);
                session.Remove(CountKey);
                responseCookies.Delete(CartKey);
                responseCookies.Delete(CountKey);
            }
            else {
                session.SetObject<List<CartItem>>(CartKey, items);
                session.SetInt32(CountKey, items.Count);
                responseCookies.SetObject<List<CartItemDTO>>(CartKey, items.ToDTO());
                responseCookies.SetInt32(CountKey, items.Count);
            }
        }
    }
}

game/GameStuff/GameStuff/Models/ViewModels/CartViewModel.cs
using System.Collections.Generic;

namespace GameStuff.Models
{
    public class CartViewModel 
    {
        public IEnumerable<CartItem> List { get; set; }
        public double Subtotal { get; set; }
        public RouteDictionary GameGridRoute { get; set; }
    }
}

game/GameStuff/GameStuff/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using GameStuff.Models;

namespace GameStuff.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private Repository<Game> data { get; set; }
        public CartController(GameStuffContext ctx) => data = new Repository<Game>(ctx);


        private Cart GetCart()
        {
            var cart = new Cart(HttpContext);
            cart.Load(data);
            return cart;
        }

        public ViewResult Index() 
        {
            var cart = GetCart();
            var builder = new GamesGridBuilder(HttpContext.Session);

            var vm = new CartViewModel {
                List = cart.List,
                Subtotal = cart.Subtotal,
                GameGridRoute = builder.CurrentRoute
            };
            return View(vm);
        }

        [HttpPost]
        public RedirectToActionResult Add(int id)
        {
            var game = data.Get(new QueryOptions<Game> {
                Include = "GameDevelopers.Developer, Genre",
                Where = b => b.GameId == id
            });
            if (game == null){
                TempData["message"] = "Unable to add game to cart.";   
            }
            else {
                var dto = new GameDTO();
                dto.Load(game);
                CartItem item = new CartItem {
                    Game = dto,
                    Quantity = 1  // default value
                };

                Cart cart = GetCart();
                cart.Add(item);
                cart.Save();

                TempData["message"] = $"{game.Title} added to cart";
            }

            var builder = new GamesGridBuilder(HttpContext.Session);
            return RedirectToAction("List", "Game", builder.CurrentRoute);
        }

        [HttpPost]
        public RedirectToActionResult Remove(int id)
        {
            Cart cart = GetCart();
            CartItem item = cart.GetById(id);
            cart.Remove(item);
            cart.Save();

            TempData["message"] = $"{item.Game.Title} removed from cart.";
            return RedirectToAction("Index");
        }
                
        [HttpPost]
        public RedirectToActionResult Clear()
        {
            Cart cart = GetCart();
            cart.Clear();
            cart.Save();

            TempData["message"] = "Cart cleared.";
            return RedirectToAction("Index");
        }


        public IActionResult Edit(int id)
        {
            Cart cart = GetCart();
            CartItem item = cart.GetById(id);
            if (item == null)
            {
                TempData["message"] = "Unable to locate cart item";
                return RedirectToAction("List");
            }
            else
            {
                return View(item);
            }
        }

        [HttpPost]
        public RedirectToActionResult Edit(CartItem item)
        {
            Cart cart = GetCart();
            cart.Edit(item);
            cart.Save();

            TempData["message"] = $"{item.Game.Title} updated";
            return RedirectToAction("Index");
        }

        public ViewResult Checkout() => View();
    }
}

game/GameStuff/GameStuff/Controllers/DeveloperController.cs
using Microsoft.AspNetCore.Mvc;
using GameStuff.Models;

namespace GameStuff.Controllers
{
    public class DeveloperController : Controller
    {
        private Repository<Developer> data { get; set; }
        public DeveloperController(GameStuffContext ctx) => data = new Repository<Developer>(ctx);

        public IActionResult Index() => RedirectToAction("List");

        public ViewResult List(GridDTO vals)
        {
            string defaultSort = nameof(Developer.DevName);
            var builder = new GridBuilder(HttpContext.Session, vals, defaultSort);
            builder.SaveRouteSegments();

            var options = new QueryOptions<Developer> {
                Include = "GameDevelopers.Game",
                PageNumber = builder.CurrentRoute.PageNumber,
                PageSize = builder.CurrentRoute.PageSize,
                OrderByDirection = builder.CurrentRoute.SortDirection
            };
            if (builder.CurrentRoute.SortField.EqualsNoCase(defaultSort))
                options.OrderBy = a => a.DevName;
            else
                options.OrderBy = a => a.DevName;

            var vm = new DeveloperListViewModel {
                Developers = data.List(options),
                CurrentRoute = builder.CurrentRoute,
                TotalPages = builder.GetTotalPages(data.Count)
            };

            return View(vm);
        }

        public IActionResult Details(int id)
        {
            var developer = data.Get(new QueryOptions<Developer> {
                Include = "GameDevelopers.Game",
                Where = a => a.DeveloperId == id
            });
            return View(developer);
        }
    }
}

game/GameStuff/GameStuff/Views/Cart/Checkout.cshtml
@{
    ViewData["Title"] = "Checkout";
}

<h1>Checkout</h1>
<ul class="list-group">
    <li class="list-group-item bg-danger text-white">
        <h4>Thank you for your Order</h4>
</ul>

game/GameStuff/GameStuff/Views/Cart/Edit.cshtml
@model CartItem

@{
    ViewData["Title"] = " | Edit Cart";
}

<h1>Edit Cart Item</h1>
<form asp-action="Edit" method="post">
    <ul class="list-group mb-2">
        <li class="list-group-item">@Model.Game.Title</li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-1">
                    <label>Price:</label>
                </div>
                <div class="col">
                    @Model.Game.Price.ToString("c")
                </div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="form-row">
                <div class="col-1">
                    <label asp-for="Quantity">Quantity:</label>
                </div>
                <div class="col">
                    <select asp-for="Quantity" class="form-control">
                        @for (int i = 1; i <= 10; i++)
                        {
                            <option>@i</option>
                        }
                    </select>
                </div>
            </div>
        </li>
    </ul>
    <input type="hidden" asp-for="Game.GameId" />
    <input type="hidden" asp-for="Game.Title" />

    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-action="Index" asp-controller="Cart" class="btn btn-primary">Cancel</a>
</form>

game/GameStuff/GameStuff/Views/Cart/Index.cshtml
@model CartViewModel

@{
    ViewData["Title"] = " | Cart";
}

<h1>Your Cart</h1>

<form asp-action="Clear" method="post">
    <ul class="list-group mb-4">
        <li class="list-group-item">
            <div class="row">
                <div class="col">
                    Subtotal: @Model.Subtotal.ToString("c")
                </div>
                <div class="col">
                    <div class="float-right">
                        <a asp-action="Checkout" class="btn btn-primary">Checkout</a>
                        <button type="submit" class="btn btn-primary">Clear Cart</button>
                        <a asp-action="List" asp-controller="Game"
                           asp-all-route-data="@Model.GameGridRoute">Back to Shopping</a>
                    </div>
                    
                </div>
            </div>
        </li>
    </ul>
</form>
<form asp-action="Remove" method="post">
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th>Image</th>
            <th>Title</th>
            <th>Developer(s)</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Subtotal</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
            @foreach (CartItem item in Model.List)  {
                <tr>
                    <td><img src="~/images/@item.Game.Image" width="200" height="200" /></td>
                    <td>
                        <a asp-action="Details" asp-controller="Game"
                           asp-route-id="@item.Game.GameId"
                           asp-route-slug="@item.Game.Title.Slug()">
                            @item.Game.Title
                        </a>
                    </td>
                    <td>
                        @foreach (var keyValuePair in item.Game.Developers)
                        {
                            <p>
                                <a asp-action="Details" asp-controller="Developer"
                                   asp-route-id="@keyValuePair.Key"
                                   asp-route-slug="@keyValuePair.Value.Slug()">
                                    @keyValuePair.Value
                                </a>
                            </p>
                        }
                    </td>
                    <td>@item.Game.Price.ToString("c")</td>
                    <td>@item.Quantity</td>
                    <td>@item.Subtotal.ToString("c")</td>
                    <td>
                        <div class="float-right">
                            <a asp-action="Edit" asp-controller="Cart"
                               asp-route-id="@item.Game.GameId"
                               asp-route-slug="@item.Game.Title.Slug()"
                               class="btn btn-primary">Edit</a>
                            <button type="submit" name="id" value="@item.Game.GameId"
                                    class="btn btn-primary">Remove</button>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>